# Generated by Django 4.1.7 on 2023-05-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Materiel",
            fields=[
                ("numMateriel", models.AutoField(primary_key=True, serialize=False)),
                ("design", models.CharField(max_length=255)),
                ("etat", models.CharField(max_length=255)),
                ("quantite", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="Produit",),
    ]
